### ISSUE TITLE
(robot) Automatically determine the exposure time or number of filters to protect the detector

### ISSUE THREAD

**Issue by MehmetTopsakal** [xpdAcq/mission-control#139] opened 2018-09-04 15:20 UTC

**Comment by CJ-Wright** [comment] 2018-09-04 15:26
xref: https://github.com/xpdAcq/mission-control/issues/10

**Comment by CJ-Wright** [comment] 2018-09-06 14:36
I'm going to close this issue as a duplicate of #10, please feel free to comment there.

**Closed by CJ-Wright** 2018-09-06 14:36 UTC
