### ISSUE TITLE
Clean End Beam Time

### ISSUE THREAD

**Issue by sghose** [xpdAcq/mission-control#42] opened 2017-10-02 18:56 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.

## Context
Some time _end_beamtime does not delete files from xpdUSER folder and hence a clean start_beamtime could not be started

### Priority
Need to be fixed ASAP, it creates problem to almost every user

## Your Environment
ONE

##Possible Solution
Sometime when the sample spreadsheet is opened and we do _end_beamtime it creates this issue. If you close and then do _end _beamtime it does not.

**Comment by sbillinge** [comment] 2017-10-03 14:27
Great, thanks for this feedback.  Very helpful to have this @sghose !

Per @CJ-Wright this may be related to an open excel instance.

We want to fix this, so epicing it.  We will try and reproduce the error in our simulator and come up with a good solution

**Comment by chiahaoliu** [comment] 2017-10-05 15:11
We can reproduce the error in our simulation environment systematically.

The reason for this error is that ``python`` in principle can't remove/close a file that is using by other applications. Therefore,  if the excel spreadsheet is open, then ``_end_beamtime`` will not be able to remove ``Import`` directory. Non-empty ``xpdUser`` will lead to an error when ``_start_beamtime``, as we expect it to be the clean.

There could be a way to have ``python`` kill other applications via subprocess, but it is pontentially dangerous. I am thinking including a print statement during ``end_beamtime`` which tells user to close the spreadsheet before the step of flushing the directories. Does it make sense? 

Attn: @sghose

**Comment by sbillinge** [comment] 2017-10-06 20:59
this seems brittle unless end_beamtime() refuses to run if it finds a lock
on a file in xpdUsers.  Is there a way to check from python or from bash if
any files have locks on them?  If yes this would give better behavior.

If not, a possible scenario would be for end_beamtime() to check if
xpdUsers is empty after running.  If not (because of the lock), it hangs
and asks the user to close excel and any programs that may be using files
in the xpdUser area, then user requests it to continue and it copies files
to archive and then deletes everything, and keeps checking until everything
is gone.

**Comment by CJ-Wright** [comment] 2017-10-06 21:38
We could have a while loop which checks if the directory exists and tries to remove the directory. This could include a print statement about closing everything. This will block the terminal until the folder is removed.

**Comment by sbillinge** [comment] 2017-10-06 22:16
sounds like a reasonable fix

**Comment by CJ-Wright** [comment] 2017-10-06 22:18
Needs a nicer print and an actual remove dir command, but might work?
```python
while os.path.exists('dir_to_be_removed'):
    try:
        'remove_dir'
    except:
        print('can't remove dir close things')
```

**Comment by sbillinge** [comment] 2017-10-07 15:24
Suggest add to 18–1 milestone

**Comment by CJ-Wright** [comment] 2017-10-07 16:50
Sure

**Comment by chiahaoliu** [comment] 2018-01-15 21:41
Closes via [PR 473](https://github.com/xpdAcq/xpdAcq/pull/473) in ``xpdAcq``.

**Closed by chiahaoliu** 2018-01-15 21:41 UTC
Labels: Epic
