### ISSUE TITLE
xrun.abort does not close fast shutter

### ISSUE THREAD

**Issue by DanOlds** [xpdAcq/mission-control#151] opened 2018-10-30 21:34 UTC
When xrun.abort is run (after ctrl+c is used to exit a script), the fast shutter is not automatically closed. 

## Expected Behavior

Ideally, xrun.abort should close the fast shutter to help preserve the detector against unnecessary exposure.

## Current Behavior

While the fast shutter can be closed manually using the CS interface, users are often unaware of this issue. 

## Possible Solution

xrun.abort should close the fast shutter if it is open, and keep it closed if it is already closed.

## Steps to Reproduce (for bugs)

1.  Start a run.
2.  ctrl-c once the measurement starts (after dark is collected)
3.  xrun.abort()

## Context

This can be a problem for strongly scattering materials, leading to unnecessary detector exposure. 

### Priority

Many photons died bringing you this request.

## Your Environment

28-ID-1 and, presumably, 28-ID-2

**Comment by sbillinge** [comment] 2018-10-30 22:19
Thanks so much for this Dan.

**Comment by CJ-Wright** [comment] 2018-10-30 23:21
@chiahaoliu should this be run through a message mutator looking at stop docs?

**Comment by chiahaoliu** [comment] 2018-10-31 02:41
@CJ-Wright We have a finalizer that should ensure the fast shutter is closed after a scan. I am wondering what happens if you do

`xrun.halt()` or `xrun.stop()`

cc: @DanOlds

**Comment by CJ-Wright** [comment] 2018-10-31 03:01
They should all issue stop documents (except for the emergency stop)

**Comment by sbillinge** [comment] 2018-10-31 12:55
I think the question is whether they also close the fast shutter?

@DanOlds pointed out an important point.  I think our general philosophy is
that the fast-shutter state should be "normally closed", so that it is
always explicitly opened before a light-exposure.  If that is true, then I
think Dan's requested behavior for the xrun.abort() is the the desired
behavior, so don't we just need to add a shutter close statement to the
abort logic, or figure out why it is not working if it is already there?

Let's schedule this for the next release and assign it to someone (maybe
this could be @DanOlds 's issue!).  It seems important but quick to me,
unless I am missing something.

S

**Comment by chiahaoliu** [comment] 2018-11-02 16:45
Tested at beamline yesterday. I confirmed neither `xrun.abort()`, `xrun.stop()` or `xrun.halt()` will close the shutter.

Our current logic is the same as the way @sbillinge described. We only open the shutter before collecting data and use `finalize_wrapper` to [close the shutter](https://github.com/xpdAcq/xpdAcq/blob/master/xpdacq/xpdacq.py#L754-L762). From the documentation, it seems this behavior should happen anyway even if the run is aborted. 

Maybe @tacaswell or @danielballan can give some comments?

**Comment by CJ-Wright** [comment] 2018-11-02 18:07
`halt` shouldn't close the shutter, since that is emergency stop.

**Comment by sbillinge** [comment] 2019-01-03 18:45
This is a good issue to work together with Dan and Tim to have Dan PR a solution as a first issue.

**Comment by tacaswell** [comment] 2019-01-22 00:11
One hook you have to this is to implement a 'stop' method on the shutter that ensures it is closed (which will happen even on `halt` as it is in the `finally` block of the RE loop, not done via a message).

However, it looks like you only install that `finalize_wrapper` if `glbl["shutter_control"]` is `True`, is opening the shutter also symmetrically controlled?

**Comment by CJ-Wright** [comment] 2019-01-22 00:13
yes, we have both open and close plan stubs: https://github.com/xpdAcq/xpdAcq/blob/master/xpdacq/beamtime.py#L145

**Comment by CJ-Wright** [comment] 2019-02-05 16:10
@DanOlds would you be able to test this with the new software?

**Comment by DanOlds** [comment] 2019-02-05 16:57
I will, once it is installed.

**Comment by CJ-Wright** [comment] 2019-02-05 17:11
Thank you!

**Comment by DanOlds** [comment] 2019-02-25 18:08
xrun.abort() still does not close the fast shutter.

**Comment by danielballan** [comment] 2019-03-02 15:39
> One hook you have to this is to implement a 'stop' method on the shutter that ensures it is closed (which will happen even on halt as it is in the finally block of the RE loop, not done via a message).

This suggestion of @tacaswell's seems the simplest way to ensure that the shutter closes when the RunEngine aborts.

**Comment by CJ-Wright** [comment] 2019-03-02 16:41
I thought that was ``finalize_wrapper`` did.

**Comment by danielballan** [comment] 2019-03-02 20:49
Oh, no, `finalize_wrapper` adds messages to be run at the end of a plan even if that plan ends due to error. The `stop()` method on `Device` is always called by the RunEngine upon exit, regardless of the plan or the exit mode (success/stop/abort/halt).

**Comment by CJ-Wright** [comment] 2019-03-02 21:28
Right, so I'm confused as to why the messages from the `finalize_wrapper` aren't being acted upon.

**Comment by danielballan** [comment] 2019-03-03 15:27
Without more context, I can't say. My point is that if the desired outcome is to always close the shutter on exit,  implementing `stop()` is a simpler way. But it may not be the correct approach in your case --- up to you.

**Comment by CJ-Wright** [comment] 2019-03-03 15:42
I guess I'm trying to figure out if there is an error in ``finalize_wrapper`` more globally.

**Comment by danielballan** [comment] 2019-03-04 14:47
There are no known problems with `finalize_wrapper`. If you asking for support on a suspected bug with `finalize_wrapper`, it would be helpful to see the plan (or ideally an [SSCCE](http://sscce.org/) reduction of the plan) and [DEBUG-level logging output](https://nsls-ii.github.io/bluesky/debugging.html#useful-snippets) to show what the resultant messages are.

**Comment by CJ-Wright** [comment] 2019-03-06 20:33
Fixed via: https://github.com/NSLS-II-PDF/profile_collection/pull/6 ?

**Comment by DanOlds** [comment] 2019-03-20 03:55
Tested and working!

**Comment by tacaswell** [comment] 2019-03-20 19:27
You probably also want to implement resume to re-open the shutter if the user chooses not to stop/abort/halt.

**Closed** 2019-03-20 19:48 UTC
