### ISSUE TITLE
(robot) Automatically find the center of sample

### ISSUE THREAD

**Issue by MehmetTopsakal** [xpdAcq/mission-control#138] opened 2018-09-04 15:18 UTC
We need robot automatically find the center of the sample.
This was needed in the previous experiment "Okuniewski_June 2018"
We will need this for upcoming beamtime early October.

**Comment by CJ-Wright** [comment] 2018-09-06 14:37
I'm going to close this as a duplicate of #127 please feel free to comment there.

**Closed by CJ-Wright** 2018-09-06 14:37 UTC
